### ISSUE TITLE
实现一个用于定义state的helper class或者DSL

### ISSUE THREAD

**Issue by YuKitAs** [xiGUAwanOU/text-based-game#18]
Implement a helper class or DSL to define concrete state objects.

A state is used in state machine (#19). It represents a condition, where the game provides certain information and/or options for user and waits for user's input.

A state object should contain three methods `on_enter`, `on_exit` and `on_input`.

* `on_input(context, input)`: once a user has selected an option or entered some input, this method of the current state is called with the user's input and current game process. The return value of this method could be:
  * An identity of a state: which will set the current state of the state machine to the state that the identity refers to;
  * A hash with:
    1. identity of a sub state machine: which will activate the forwarding mode of the state machine with the sub state machine;
    2. identity of a state: after finishing the forwarding mode, state machine will continue to run starting from the specified state.
* `on_enter(context)`: will be called every time on the current state after it has been changed.
* `on_exit(context)`: will be called every time on the current state before it has been changed.

The parameter `context` is a set of shared data available for all states in the current state machine, state machine does not care about the content of the context.

**Comment by xiGUAwanOU** [comment]
该部分已实现，决定经过refactor后与 #19 合并。
