### ISSUE TITLE
实现state machine

### ISSUE THREAD

**Issue by YuKitAs** [xiGUAwanOU/text-based-game#19]
A state machine is an abstract of a user interaction process. Each state in a state machine represents a condition, where the game is providing some information and/or options to the player, while waiting for the answer from the player.

State machine can run in 2 different modes:
* "running" mode: will be active if the current state is a real state. The state machine will act as a "normal" state machine in this mode.
* "forwarding" mode: will be active if the current state is another (sub) state machine. It does nothing but only forwards player's input to the sub state machine.

A state machine exposes these methods: `reset`, `on_input`

* `reset()`: will reset the state machine to the initial configuration;
* `on_input(input)`: accept a player's input. This method returns a bool value: if true, the state machine should be kept running; if false, the statue machine should be stopped.

**Comment by xiGUAwanOU** [comment]
经过商讨之后 #18 与 #19 决定合并。因为从使用者的角度来讲，把state当作自动机的一部分来定义，比单独定义state，再在自动机中引用state要来得方便得多。而且整体也有一些统一感。

故新的DSL的样式应该为：
```ruby
StateMachineClass.define "StateMachineA" do
  states [:state_a, StateMachineB, :exit]  # StateMachineB has already been defined somewhere else
  start_state :state_a
  end_states [:exit]

  transition :state_a, StateMachineB do |context, input|
    if input ...
      return true
    else
      return false
  end

  transition StateMachineB, :state_a do |context, input|
    return true
  end

  transition :state_a, :exit do |context, input|
    if input ...
      return ture
    else
      return false
  end
end
```

其中`transition`的第一个参数为当前状态，第二个为目标状态，第三个block为状态转移条件，如果返回true则进行状态转移，如果返回false则不进行。另，如果多个transition有相同的第一个参数，并且都会返回true的话，则根据transition的定义顺序选取第一个返回true的条件进行状态转移（防止non-deterministic的情况）。

**Comment by YuKitAs** [comment]
目的：使用自动机处理游戏过程中每一步的玩家输入。

```
What do you want to do? 
1. Move 2. Look
> Look
This is the backyard of Whatever Magical School. What do you want to check?
1. Master 2. Tree 3. Magical Well 4. Back
> Magical Well
...
```

以上示例中，进入游戏后，玩家选择`Look`，自动机切换状态后显示新的选项，玩家选择`Magical Well`，自动机又将切换到下一状态。

自动机类型：带context的Mealy DEA。状态切换由当前状态和输入决定。

流程：
0 玩家输入选项
1 当前状态为普通state ? goto A.1 : goto B.1

A.1 statemachine根据玩家输入和当前状态确定下一状态并输出信息
A.2 切换状态(上一步选项消失)并 goto 0

B.1 statemachine将输入传给sub statemachine
B.2 sub statemachine已到达final state ? goto B.3 : goto 0
B.3 statemachine确定下一状态并输出信息
B.4 切换状态(上一步选项消失)并 goto 0
